global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'Gmai Adress'
  smtp_auth_username: 'Gmail Adress'
  smtp_auth_password: 'App Password'

route:
  receiver: 'email-alerts'
  group_wait: "30s"
  group_interval: "5m"
  repeat_interval: "4h"

receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'email adress'
